# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleTakeAway' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleTakeAway
  
    pod 'Alamofire', '4.8.2'
    pod 'SwiftyJSON'
    pod 'NVActivityIndicatorView'
    pod 'Kingfisher'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'Cosmos', '~> 19.0'
    pod 'DropDown'

  target 'SampleTakeAwayTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '4.8.2'
    pod 'SwiftyJSON'
    pod 'NVActivityIndicatorView'
    pod 'Kingfisher'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'Cosmos', '~> 19.0'
    pod 'DropDown'
  end

  target 'SampleTakeAwayUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '4.8.2'
    pod 'SwiftyJSON'
    pod 'NVActivityIndicatorView'
    pod 'Kingfisher'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'Cosmos', '~> 19.0'
    pod 'DropDown'
  end

end
